############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2


[[main]]
name = "Projects"
url = "blog/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

